# Generated by Django 2.1.7 on 2019-05-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Configuration key')),
                ('value', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Configuration value')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='configuration',
            unique_together={('key', 'value')},
        ),
    ]
