# Generated by Django 2.1.7 on 2019-05-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('label', models.CharField(db_index=True, max_length=30, verbose_name='Image label')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
