# Generated by Django 2.1.7 on 2019-05-14 20:36

from django.db import migrations
from blocks.models import AnimationName, AnimationTrigger

import anki_vector

def generate_names(apps, schema_editor):
  """
  Helper function to populate names of animations and triggers and update their status
  """

  def __update_or_create(source, name):
    """
    Helper function to create/update a single name index
    """
    source.objects.update_or_create(
        name=name, 
        defaults={
            'name': name,
            'active': True
        })

  AnimationName = apps.get_model('blocks', 'AnimationName')
  AnimationName.objects.filter(active=True).update(active=False)

  AnimationTrigger = apps.get_model('blocks', 'AnimationTrigger')
  AnimationTrigger.objects.filter(active=True).update(active=False)

  with anki_vector.AsyncRobot() as robot:
    anim_request = robot.anim.load_animation_list()
    anim_request.result()
    for anim_name in robot.anim.anim_list:
      __update_or_create(AnimationName, anim_name)

    anim_trigger_request = robot.anim.load_animation_trigger_list()
    anim_trigger_request.result()
    for anim_trigger_name in robot.anim.anim_trigger_list:
      __update_or_create(AnimationTrigger, anim_trigger_name)

# ----------------------

class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(generate_names),
    ]
