# Generated by Django 2.1.7 on 2019-05-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_initialize_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=25, unique=True, verbose_name='Animation tag')),
            ],
        ),
        migrations.AddField(
            model_name='animationname',
            name='tags',
            field=models.ManyToManyField(to='blocks.AnimationTags'),
        ),
        migrations.AddField(
            model_name='animationtrigger',
            name='tags',
            field=models.ManyToManyField(to='blocks.AnimationTags'),
        ),
    ]
