# Generated by Django 2.1.7 on 2019-05-15 18:23
from django.db import migrations
from blocks.models import AnimationName, AnimationTrigger, AnimationTags

def generate_tags(apps, schema_editor):
  """
  Helper function to populate labels for animations and triggers and update their status
  """

  def __update_tags_in(source):
    """
    Helper function to iterate over given sources and tag its objects
    """
    for entry in source.objects.filter(active=True):
      tags = AnimationTags.parse_tags(entry.name)
      for tag in tags:
        entry.tags.add(tag.id)
      entry.save()

  __update_tags_in(AnimationName)
  __update_tags_in(AnimationTrigger)



class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_tagging_structure'),
    ]

    operations = [
        migrations.RunPython(generate_tags),
    ]
